[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "David Krauthamer", email = "dkrautha@pm.me"},
    {name = "Brad O'Connel", email = ""},
]
dependencies = [
    "pandas>=2.0.0",
    "pyarrow>=11.0.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
